-- MySQL Script generated by MySQL Workbench
-- Fri Mar  1 21:11:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MySQLFirst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MySQLFirst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MySQLFirst` DEFAULT CHARACTER SET utf8 ;
USE `MySQLFirst` ;

-- -----------------------------------------------------
-- Table `MySQLFirst`.`User_T`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLFirst`.`User_T` (
  `user_email` VARCHAR(200) NOT NULL,
  `user_password` VARCHAR(200) NOT NULL,
  `user_name` VARCHAR(200) NOT NULL,
  `user_dob` DATE NOT NULL,
  `user_gender` CHAR(1) NOT NULL,
  `user_phone` VARCHAR(45) NOT NULL,
  `user_prefs` VARCHAR(10000) NULL,
  `user_address` VARCHAR(100) NULL,
  `user_country` VARCHAR(45) NOT NULL,
  `user_profession` VARCHAR(45) NULL,
  `user_organization` VARCHAR(200) NULL,
  PRIMARY KEY (`user_email`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLFirst`.`Vendor_T`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLFirst`.`Vendor_T` (
  `vendor_username` VARCHAR(200) NOT NULL,
  `vendor_password` VARCHAR(200) NOT NULL,
  `vendor_name` VARCHAR(200) NULL,
  `vendor_phone` VARCHAR(45) NULL,
  `vendor_location` VARCHAR(200) NULL,
  `vendor_tag` VARCHAR(200) NULL,
  `vendor_address` VARCHAR(45) NULL,
  PRIMARY KEY (`vendor_username`),
  UNIQUE INDEX `vendor_email_UNIQUE` (`vendor_username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLFirst`.`Product_T`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLFirst`.`Product_T` (
  `product_id` INT GENERATED ALWAYS AS (),
  `product_name` VARCHAR(200) NOT NULL,
  `product_price` INT NOT NULL,
  `product_tag` VARCHAR(200) NULL,
  `vendor_username` VARCHAR(200) NOT NULL,
  `product_offered` BIT NULL DEFAULT 0,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `product_name_UNIQUE` (`product_name` ASC) VISIBLE,
  INDEX `fk_Product_T_Vendor_T_idx` (`vendor_username` ASC) VISIBLE,
  CONSTRAINT `fk_Product_T_Vendor_T`
    FOREIGN KEY (`vendor_username`)
    REFERENCES `MySQLFirst`.`Vendor_T` (`vendor_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MySQLFirst`.`Purchase_T`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MySQLFirst`.`Purchase_T` (
  `purchase_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `user_email` VARCHAR(200) NOT NULL,
  `product_id` INT NOT NULL,
  `purchase_time` DATETIME NOT NULL,
  `purchase_finalized` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`purchase_id`),
  UNIQUE INDEX `purchase_id_UNIQUE` (`purchase_id` ASC) VISIBLE,
  INDEX `fk_Purchase_T_User_T1_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_Purchase_T_Product_T1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_T_User_T1`
    FOREIGN KEY (`user_email`)
    REFERENCES `MySQLFirst`.`User_T` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_T_Product_T1`
    FOREIGN KEY (`product_id`)
    REFERENCES `MySQLFirst`.`Product_T` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
